-- Seed: 50 additional achievements for HabitTracker
-- Adjust table/column names if your schema differs. Run in Supabase SQL editor.

INSERT INTO public.achievements (name, description, icon, category, tier, points, requirement_type, requirement_value, is_secret)
VALUES
('Quick Starter', 'Complete your first habit within 24 hours of signup', 'rocket', 'milestones', 'bronze', 10, 'total_completions', 1, FALSE),
('Consistent Week', 'Complete a habit every day for 7 days', 'calendar', 'streaks', 'bronze', 50, 'streak_days', 7, FALSE),
('Two-Week Soldier', 'Maintain a 14-day streak on any habit', 'flame', 'streaks', 'silver', 80, 'streak_days', 14, FALSE),
('Month Maker', 'Maintain a 30-day streak', 'rocket', 'streaks', 'gold', 200, 'streak_days', 30, FALSE),
('Century Club', 'Complete 100 habit completions', 'trophy', 'completion', 'silver', 200, 'total_completions', 100, FALSE),
('Milestone 250', 'Complete 250 habit completions', 'medal', 'completion', 'gold', 400, 'total_completions', 250, FALSE),
('Milestone 500', 'Complete 500 habit completions', 'medal', 'completion', 'gold', 1000, 'total_completions', 500, FALSE),
('Habit Builder', 'Create 5 habits', 'build', 'milestones', 'bronze', 25, 'habit_count', 5, FALSE),
('Habit Architect', 'Create 20 habits', 'briefcase', 'milestones', 'gold', 150, 'habit_count', 20, FALSE),
('First Challenge', 'Complete your first challenge', 'ribbon', 'challenges', 'bronze', 50, 'challenge_wins', 1, FALSE),
('Challenge Champion', 'Complete 10 challenges', 'podium', 'challenges', 'gold', 500, 'challenge_wins', 10, FALSE),
('Social Starter', 'Add your first friend', 'people', 'social', 'bronze', 10, 'friend_count', 1, FALSE),
('Connector', 'Add 5 friends', 'people', 'social', 'silver', 30, 'friend_count', 5, FALSE),
('Social Butterfly', 'Add 20 friends', 'people', 'social', 'gold', 100, 'friend_count', 20, FALSE),
('Profile Pro', 'Upload a profile photo', 'person', 'milestones', 'bronze', 5, 'custom', NULL, FALSE),
('Bio Boss', 'Write a profile bio', 'document-text', 'milestones', 'bronze', 5, 'custom', NULL, FALSE),
('Reminder Rookie', 'Enable your first reminder', 'alarm', 'milestones', 'bronze', 10, 'custom', NULL, FALSE),
('Reminder Regular', 'Use reminders for 5 habits', 'alarm', 'milestones', 'silver', 25, 'habit_count', 5, FALSE),
('Streak Saver', 'Recover a broken streak within 48 hours', 'heart', 'streaks', 'silver', 40, 'custom', NULL, FALSE),
('Weekend Warrior', 'Complete a habit every weekend for 4 consecutive weekends', 'calendar', 'streaks', 'silver', 60, 'streak_days', 28, FALSE),
('Hydration Hero', 'Complete 30 water habit days', 'water', 'milestones', 'bronze', 30, 'total_completions', 30, FALSE),
('Step Strider', 'Reach 10k steps in a day', 'walk', 'milestones', 'bronze', 10, 'custom', NULL, FALSE),
('Step Streak', 'Reach 10k steps 7 times', 'walk', 'streaks', 'silver', 50, 'custom', 7, FALSE),
('Reading Regular', 'Read daily for 14 days in a row', 'book', 'milestones', 'silver', 40, 'streak_days', 14, FALSE),
('Language Learner', 'Practice a language for 30 days', 'language', 'milestones', 'gold', 120, 'streak_days', 30, FALSE),
('Mindful Minute', 'Complete 100 minutes of mindfulness', 'sunny', 'milestones', 'bronze', 20, 'total_completions', 100, FALSE),
('Meditation Master', 'Meditate daily for 30 days', 'lotus', 'milestones', 'gold', 150, 'streak_days', 30, FALSE),
('Fitness Fanatic', 'Complete 50 workout sessions', 'barbell', 'milestones', 'gold', 200, 'total_completions', 50, FALSE),
('Calm Nights', 'Avoid screens 14 nights in a row', 'eye-off', 'milestones', 'silver', 60, 'streak_days', 14, FALSE),
('No-Snoozer', 'Wake on first alarm for 14 days', 'alarm', 'streaks', 'silver', 50, 'streak_days', 14, FALSE),
('Healthy Eater', 'Log healthy meals for 21 days', 'restaurant', 'milestones', 'silver', 80, 'total_completions', 21, FALSE),
('Sugar-Free Two-Week', 'Avoid added sugar for 14 days', 'cafe', 'milestones', 'gold', 120, 'streak_days', 14, FALSE),
('Cold Shower Cadet', 'Finish with cold water for 7 days', 'thermometer', 'milestones', 'bronze', 20, 'streak_days', 7, FALSE),
('Cold Shower Veteran', 'Cold shower for 14 days', 'thermometer', 'milestones', 'silver', 60, 'streak_days', 14, FALSE),
('Daily Journal', 'Write journal entries for 21 days', 'pencil', 'milestones', 'silver', 60, 'total_completions', 21, FALSE),
('Declutter Dynamo', 'Declutter for 21 days', 'trash', 'milestones', 'silver', 60, 'total_completions', 21, FALSE),
('Digital Minimalist', 'Complete 14 days of digital declutter', 'trash-outline', 'milestones', 'bronze', 30, 'streak_days', 14, FALSE),
('Finance Starter', 'Log expenses for 7 days', 'card', 'milestones', 'bronze', 15, 'total_completions', 7, FALSE),
('Budget Builder', 'Maintain budget tracking for 30 days', 'cash', 'milestones', 'silver', 75, 'total_completions', 30, FALSE),
('Code Cadet', 'Code for 20 minutes a day for 14 days', 'code-slash', 'milestones', 'bronze', 40, 'streak_days', 14, FALSE),
('Open Source Contributor', 'Make your first open-source contribution', 'git-commit', 'milestones', 'gold', 300, 'custom', NULL, FALSE),
('Gratitude Guru', 'Write gratitude entries for 14 days', 'heart', 'milestones', 'silver', 40, 'streak_days', 14, FALSE),
('Volunteer Virtue', 'Complete 5 volunteer activities', 'hand-heart', 'social', 'silver', 80, 'total_completions', 5, FALSE),
('Sleep Steward', 'Follow a sleep routine for 10 days', 'moon', 'milestones', 'bronze', 25, 'streak_days', 10, FALSE),
('Night Owl No More', 'Finish 14 nights with consistent bedtime', 'moon', 'milestones', 'silver', 50, 'streak_days', 14, FALSE),
('Streak Collector', 'Hold three different 7-day streaks', 'star', 'streaks', 'gold', 200, 'custom', NULL, FALSE),
('Consistency King', 'Maintain any habit for 90 days', 'crown', 'streaks', 'diamond', 1000, 'streak_days', 90, FALSE),
('Century Completer', 'Complete habits 100 times', 'checkmark-circle', 'completion', 'gold', 200, 'total_completions', 100, FALSE),
('500 Club', 'Complete habits 500 times', 'medal', 'completion', 'diamond', 1000, 'total_completions', 500, FALSE),
('Quick Responder', 'Reply to 10 messages in app support thread', 'chatbox-ellipses', 'social', 'bronze', 10, 'custom', NULL, FALSE),
('Photo Collector', 'Upload 10 habit photos', 'camera', 'milestones', 'silver', 40, 'custom', 10, FALSE)
ON CONFLICT (name) DO NOTHING;
