-- INSERT statements for `challenge_templates` table
-- Adjust column names if your schema differs. Run in Supabase SQL editor.

INSERT INTO public.challenge_templates (name, description, duration_days, required_completions, difficulty, color, icon, is_premium, created_at)
VALUES
('7-Day Mindful Mornings', 'Wake up 10 minutes earlier and follow a short mindfulness or breathing routine each morning.', 7, 7, 'easy', '#FF6B6B', 'sunny', false, now()),
('14-Day Gratitude Journal', 'Write three things you are grateful for every evening to build an attitude of gratitude.', 14, 14, 'easy', '#FFD93D', 'book', false, now()),
('21-Day Walk Streak', 'Walk at least 20 minutes every day — get moving and clear your head.', 21, 21, 'medium', '#4CAF50', 'walk', false, now()),
('30-Day Water Boost', 'Drink 8 glasses of water each day to stay hydrated and feel better.', 30, 30, 'easy', '#34C6F1', 'water', false, now()),
('14-Day No-Snooze', 'Get out of bed on first alarm — break the snooze habit and start your day strong.', 14, 14, 'medium', '#FF8C42', 'alarm', false, now()),
('30-Day Read Daily', 'Read at least 20 minutes every day to build knowledge and focus.', 30, 30, 'easy', '#7F5AF0', 'book-outline', false, now()),
('14-Day Evening Screen-Free', 'Avoid screens for 1 hour before bed to improve sleep quality.', 14, 14, 'medium', '#FF6BAC', 'eye-off', false, now()),
('21-Day Push-Up Builder', 'Do a short push-up set each day, gradually increasing reps to build upper-body strength.', 21, 21, 'medium', '#F44336', 'barbell', false, now()),
('30-Day Plank Challenge', 'Hold a plank daily and increase duration over 30 days to build core strength.', 30, 30, 'hard', '#FF4D6D', 'fitness', false, now()),
('14-Day Sugar Cut', 'Avoid added sugars and sugary drinks for two weeks to reset cravings.', 14, 14, 'hard', '#C62828', 'cafe', true, now()),
('7-Day Daily Stretch', 'Spend 10 minutes stretching each day to improve mobility and reduce stiffness.', 7, 7, 'easy', '#00B894', 'body', false, now()),
('30-Day Language Sprint', 'Practice a new language for 15 minutes each day to build fluency.', 30, 30, 'medium', '#6C5CE7', 'language', true, now()),
('10-Day Sleep Routine', 'Follow a consistent wind-down routine each night to improve sleep quality.', 10, 10, 'easy', '#2E86AB', 'moon', false, now()),
('21-Day Declutter', 'Spend 10 minutes a day decluttering a small area — finish the month with a tidier space.', 21, 21, 'easy', '#FFB86B', 'trash', false, now()),
('14-Day No Alcohol', 'Take a two-week break from alcohol to reset your habits and energy.', 14, 14, 'hard', '#8B0000', 'wine', true, now()),
('30-Day Coding Streak', 'Code for at least 20 minutes every day to build consistency and momentum.', 30, 30, 'medium', '#0EA5A4', 'code-slash', false, now()),
('14-Day Cold Shower', 'Finish your shower with 30–60 seconds of cold water to boost alertness and resilience.', 14, 14, 'hard', '#00A3E0', 'thermometer', false, now()),
('7-Day Flossing', 'Floss every day for a week to build a lasting oral hygiene habit.', 7, 7, 'easy', '#FF6F91', 'brush', false, now()),
('30-Day 10k Steps', 'Aim for 10,000 steps per day for 30 days to build endurance and daily activity.', 30, 30, 'hard', '#3B82F6', 'walk', true, now()),
('14-Day Digital Declutter', 'Unsubscribe, organize, and delete files/emails for 15 minutes daily to declutter your digital life.', 14, 14, 'easy', '#9CA3AF', 'trash-outline', false, now()),
('5-Day Screen Detox', 'Limit social apps to 30 minutes per day for five days to reset your habits.', 5, 5, 'easy', '#F97316', 'phone-portrait', false, now()),
('7-Day Water Challenge', 'Drink 8 glasses of water every day for a week.', 7, 7, 'easy', '#34C6F1', 'water', false, now()),
('14-Day Yoga Flow', 'Follow a short yoga flow each morning for 14 days.', 14, 14, 'medium', '#7C4DFF', 'flower', false, now()),
('21-Day Declutter Sprint', 'Declutter a different area for 10 minutes each day.', 21, 21, 'easy', '#FFD580', 'trash', false, now()),
('30-Day No-Sugar Challenge', 'Avoid added sugars for 30 days.', 30, 30, 'hard', '#D32F2F', 'cafe', true, now()),
('14-Day Plant-Based', 'Eat plant-forward meals for two weeks.', 14, 14, 'medium', '#66BB6A', 'leaf', true, now()),
('21-Day Habit Builder', 'Complete your chosen habit every day for 21 days.', 21, 21, 'medium', '#4CAF50', 'checkmark-circle', false, now()),
('10-Day Sleep Wind-Down', 'Follow a relaxing routine before bed for 10 days.', 10, 10, 'easy', '#3B82F6', 'moon', false, now()),
('14-Day No-Complaints', 'Try 14 days without complaining; focus on gratitude.', 14, 14, 'hard', '#FFB74D', 'happy', false, now()),
('30-Day Steps Push', 'Hit at least 8k steps every day for 30 days.', 30, 30, 'hard', '#3B82F6', 'walk', true, now()),
('7-Day Journaling', 'Write a short journal entry each day for 7 days.', 7, 7, 'easy', '#A78BFA', 'pencil', false, now()),
('14-Day Healthy Breakfast', 'Have a balanced breakfast each morning for 14 days.', 14, 14, 'easy', '#FFB86B', 'restaurant', false, now()),
('21-Day Stretch & Move', 'Stretch or move for 10 minutes daily for 21 days.', 21, 21, 'easy', '#00B894', 'body', false, now()),
('30-Day Learn A Skill', 'Practice a new skill daily for 30 days.', 30, 30, 'medium', '#6C5CE7', 'school', true, now()),
('14-Day Mindful Eating', 'Practice mindful eating at every meal for 14 days.', 14, 14, 'medium', '#F06292', 'restaurant', false, now()),
('7-Day Declutter Challenge', 'Declutter one drawer or shelf each day for a week.', 7, 7, 'easy', '#FFD580', 'trash', false, now()),
('21-Day Meditation Habit', 'Meditate for at least 5 minutes every day.', 21, 21, 'easy', '#95E1D3', 'lotus', false, now()),
('30-Day Reading Habit', 'Read at least 20 minutes every day for 30 days.', 30, 30, 'medium', '#7F5AF0', 'book-open', false, now()),
('14-Day No-Snacking', 'Avoid unnecessary snacks between meals for 14 days.', 14, 14, 'hard', '#FF6B6B', 'nutrition', true, now()),
('7-Day Cold Shower Trial', 'End your shower with cold water for 7 days.', 7, 7, 'hard', '#00A3E0', 'thermometer', false, now()),
('21-Day Creative Sprint', 'Create something small every day for 21 days (draw, write, photo).', 21, 21, 'medium', '#FF9F1C', 'brush', false, now()),
('14-Day Sugar-Free Weekends', 'Avoid added sugar on weekends for two weeks.', 14, 14, 'medium', '#F48FB1', 'cafe', false, now()),
('30-Day Productivity Boost', 'Do one focused work session each day for 30 days.', 30, 30, 'hard', '#0EA5A4', 'speedometer', true, now()),
('10-Day Breathwork', 'Practice a breathwork routine daily for 10 days.', 10, 10, 'easy', '#4DD0E1', 'cloud', false, now()),
('7-Day No-Alcohol Week', 'Avoid alcohol for seven days to reset habits.', 7, 7, 'medium', '#8B0000', 'wine', false, now()),
('21-Day Photo Challenge', 'Take one meaningful photo each day for 21 days.', 21, 21, 'easy', '#FF6F91', 'camera', false, now()),
('14-Day Coding Habit', 'Code daily for 20 minutes for two weeks.', 14, 14, 'medium', '#0EA5A4', 'code-slash', false, now()),
('30-Day Gratitude Practice', 'Write gratitude notes every day for 30 days.', 30, 30, 'easy', '#FFD93D', 'heart', false, now()),
('7-Day Plank Mini', 'Hold a plank each day for 7 days, increasing time gradually.', 7, 7, 'easy', '#FF4D6D', 'fitness', false, now()),
('14-Day Inbox Zero', 'Process your inbox daily for two weeks to reach inbox zero.', 14, 14, 'hard', '#9CA3AF', 'mail', false, now()),
('21-Day No-Snooze Streak', 'Wake without snoozing for 21 consecutive days.', 21, 21, 'hard', '#FF8C42', 'alarm', false, now()),
('30-Day Habit Stamina', 'Complete any chosen habit every day for 30 days.', 30, 30, 'extreme', '#F3A683', 'rocket', true, now()),
('14-Day Minimalism', 'Remove one item daily and donate or recycle it for two weeks.', 14, 14, 'easy', '#BDBDBD', 'trash-outline', false, now()),
('7-Day Mindful Commute', 'Use commute time mindfully (podcast, reflection) for 7 days.', 7, 7, 'easy', '#6C5CE7', 'train', false, now()),
('21-Day Social Fast', 'Reduce social media to 30 minutes/day for 21 days.', 21, 21, 'hard', '#F97316', 'logo-twitter', true, now()),
('14-Day Strength Starter', 'Do a short strength routine 3x per week for two weeks.', 14, 6, 'medium', '#D32F2F', 'barbell', false, now()),
('30-Day Step Up', 'Add 2k steps daily to your baseline for 30 days.', 30, 30, 'hard', '#3B82F6', 'walk', false, now()),
('10-Day Hydration Sprint', 'Hit 8 glasses a day for 10 days straight.', 10, 10, 'easy', '#34C6F1', 'water', false, now()),
('14-Day Screen Curfew', 'No screens after 9pm for two weeks.', 14, 14, 'medium', '#374151', 'eye-off', false, now()),
('7-Day Compliment Habit', 'Give a genuine compliment daily for a week.', 7, 7, 'easy', '#FFD93D', 'happy', false, now()),
('21-Day Journaling Journey', 'Journal every evening for 21 days.', 21, 21, 'easy', '#A78BFA', 'pencil', false, now()),
('30-Day Financial Check', 'Log daily expenses for 30 days.', 30, 30, 'medium', '#00B894', 'card', false, now()),
('14-Day Plant Care', 'Water and care for your plants regularly for 14 days.', 14, 14, 'easy', '#6BCF7F', 'leaf', false, now()),
('7-Day Gratitude Burst', 'Send a gratitude message each day for 7 days.', 7, 7, 'easy', '#FFB86B', 'chatbox', false, now()),
('21-Day Focus Challenge', 'Do a distraction-free work session daily for 21 days.', 21, 21, 'hard', '#0EA5A4', 'focus', true, now()),
('14-Day Walk & Talk', 'Walk and call a friend each day for 14 days.', 14, 14, 'easy', '#4CAF50', 'walk', false, now()),
('30-Day Code Review', 'Review code or learn code patterns daily for 30 days.', 30, 30, 'medium', '#6C5CE7', 'git-commit', false, now()),
('10-Day Mental Reset', 'Daily 10-minute reset routine for 10 days.', 10, 10, 'easy', '#95E1D3', 'sunny', false, now()),
('14-Day Healthy Snack', 'Choose a healthy snack each day for 14 days.', 14, 14, 'easy', '#FF6B6B', 'nutrition', false, now()),
('7-Day Language Practice', 'Practice vocabulary daily for a week.', 7, 7, 'easy', '#7F5AF0', 'language', false, now()),
('21-Day Bodyweight Builder', 'Perform a short bodyweight routine each day.', 21, 21, 'medium', '#F44336', 'barbell', false, now());
